name: Build glibc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build script as root
        run: |
          chmod +x packages/glibc/build.sh
          sudo bash packages/glibc/build.sh

      - name: Upload glibc rootfs
        uses: actions/upload-artifact@v4
        with:
          name: glibc-2.44-rootfs
          path: /build/glibc-2.44-rootfs.tar.xz
