name: Build glibc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build glibc
        run: |
          chmod +x glibc/build.sh
          docker run --rm \
            --platform linux/arm64 \
            -v "$PWD:/packages" \
            -w /packages \
            debian:bookworm \
            bash /packages/glibc/build.sh
