name: SSH to GitHub Runner

on:
  workflow_dispatch:

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix DNS
        run: |
          echo "=== Before ==="
          cat /etc/resolv.conf

          sudo bash -c 'printf "nameserver 1.1.1.1\nnameserver 8.8.8.8\n" > /etc/resolv.conf'

          echo "=== After ==="
          cat /etc/resolv.conf

          echo "=== DNS test ==="
          getent hosts ssh.tmate.io

          echo "=== HTTPS test ==="
          curl -I --connect-timeout 10 https://ssh.tmate.io

      - name: Tmate
        uses: mxschmitt/action-tmate@v3
        with:
          connect-timeout-seconds: 60
